### ISSUE TITLE
Capital letters in titles

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-block_advnotifications#1]
The default Moodle language pack "en" uses capital letters in first word of multi-word titles only. The block name should be "Advanced notifications" (not Notifications). This would help to achieve consistency with the rest of standard Moodle UI.

**Comment by zpottie** [comment]
Thanks David! It's my first contribution to Moodle, so apologies for silly issues like this. Thanks again for the help though!

Updated/Fixed in 26fa411
