### ISSUE TITLE
adding rss support

### ISSUE THREAD

**Issue by js0000** [learningworks/moodle-block_advnotifications#14]
hi
i've done work to add rss support to advnotifications plugin. here's the respository URL:
https://github.com/brandeis-wmd/moodle-block_advnotifications

- the rss code was copied from blocks/rss_client
- it was integrated into the main object (might be better off done differently)
- the way it works is that if advnotifications "message" is a URL, code tries to retrieve feed and will display first description it finds in feed

i'm writing at this point to get make you aware of this work and see how it can be integrated into the plugin if desired.

so it's not really a bug, but this is a way to go forward. let me know, thx!

**Comment by zpottie** [comment]
Interesting concept - I'll leave this open for now to follow up and check out the code/implementation. 👌

**Comment by js0000** [comment]
code needs work- now pulling rss code into it's own object ... will update github repo as work continues.

**Comment by zpottie** [comment]
Seems abandoned - closing
