### ISSUE TITLE
Validation failure

### ISSUE THREAD

**Issue by zpottie** [learningworks/moodle-block_advnotifications#16]
From [Moodle.org](https://moodle.org/plugins/block_advnotifications#comment-55336-5c4a1bd2c9556)
__________________

"Hi.

I'm getting the message "Installation aborted due to validation failure" when I try to update.

Moodle 3.5.1+ (Build: 20180713)

Regards"

**Comment by zpottie** [comment]
String only appears if result returns as false (failed) while validating these:
![validate](https://user-images.githubusercontent.com/9076608/51707903-47df4880-2087-11e9-9c13-05fe7bab3023.png)

**Comment by zpottie** [comment]
User's build number is lower than required version/build number.

Required: 20181112
User's: 20180713

(Assuming user is trying to install v1.3.2 of the plugin)

**Comment by zpottie** [comment]
Reply from [Moodle.org](https://moodle.org/plugins/block_advnotifications)

__________________________

"Hi[.]
It must be the Moodle version then. The full message is:

Debugging output enabled
Downloading block_advnotifications ... 
<- https://moodle.org/plugins/download.php/18798/block_advnotifications_moodle36_2019012311.zip
-> /var/moodle_data/temp/core_plugin/code_manager/distfiles/4789cdcac10e2b655fe3e9de9a62bba9.zip ... OK
Validating block_advnotifications ... Error
[OK] Name of the plugin to be installed [advnotifications] 


[OK] Plugin version [2019012311] 
[Error] Required Moodle version [2018051703] 
Installation aborted due to validation failure

Thanks"

**Comment by mudrd8mz** [comment]
If the version numbers were correct and yet the validation still failed, it could be https://tracker.moodle.org/browse/MDL-81183
