### ISSUE TITLE
Different date format after saving a notification

### ISSUE THREAD

**Issue by FrankyJust** [learningworks/moodle-block_advnotifications#17]
When I make a new notification and put the dates into the date fields in the dd/mm/yyyy placeholder format, the dates are incorrect saved as: mm/dd/yyyy. And I have to edit the dates afterwards to solve this. When I fill it in as yyyy/mm/dd, the date fields are saved in the format dd/mm/yyyy, which is in my case the correct way to display the notification on the proper dates. I'm using Moodle 3.6 with a child theme of Boost theme. What could be the problem and solution?

**Comment by zpottie** [comment]
Hi @FrankyJust - I'm using the input type "date". If you're seeing the placeholders, it means your browser does not support this input type or is an outdated browser.

I did, however, update the placeholders as a fallback to the expected format of yyyy-mm-dd (see caad44d)

Now, if a browser does not support the "date" input type, entering the date as per the placeholders should work and the server should be able to properly interpret the input (and not swap the day/month as it did in your case).

Hope this helps.

Thanks
