### ISSUE TITLE
Improvement: convert cron to scheduled task

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-block_advnotifications#2]
https://docs.moodle.org/dev/Task_API

**Comment by mudrd8mz** [comment]
As the TODO says in the code :-)

**Comment by zpottie** [comment]
Thanks David - I will address this in the near future hopefully. 😄 

**Note:** I accidentally reference the wrong issue in my commit (ignore referenced commit above).

**Comment by zpottie** [comment]
TODO has been done. :)
