### ISSUE TITLE
Proposal: enlarge min-width of message field 

### ISSUE THREAD

**Issue by FrankyJust** [learningworks/moodle-block_advnotifications#20]
The textarea for the message field is of the same (min-)width as the title field. Although there is an option to enlarge the message field, maybe it's an idea to enlarge the min-width because a message is usually (much) larger than the title field. Visually this would be more attractive, I think.

**Comment by zpottie** [comment]
Hi @FrankyJust - I updated the width of the message field and made some other visual tweaks. I'll close this now.
