### ISSUE TITLE
Icons cannot be overwritten by theme

### ISSUE THREAD

**Issue by amandadoughty** [learningworks/moodle-block_advnotifications#21]
I expect almost all users will stick to the default alert colours and icons but we have had to change them. However they are hard coded and do not allow theme overrides.

I have attached a small patch to fix this.
[block_advnotifications.diff.txt](https://github.com/learningworks/moodle-block_advnotifications/files/3247888/block_advnotifications.diff.txt)

**Comment by emyb** [comment]
Hi @amandadoughty 

Thanks for your work on this. Are you able to submit a Pull Request? It may not get merged until the lead maintainer returns from holiday.

Cheers

**Comment by zpottie** [comment]
Hi @amandadoughty - thanks for highlighting this. I used and tweaked your patch and it is now supported in the plugin from caad44d.
