### ISSUE TITLE
How to adjust date format for USA form(MM-DD-YYYY)

### ISSUE THREAD

**Issue by jprovasnik** [learningworks/moodle-block_advnotifications#23]
Hello, 
When on the "Manage Notifications" page, I cannot find a way to adjust how the date is displayed. Currently, it's in DD-MM-YYYY and I don't see a language string to change it to MM-DD-YYYY.  Is this something that can be adjusted?

![can date be swapped](https://user-images.githubusercontent.com/44345287/86541408-a7778f80-beda-11ea-8fcf-8ddf75202d77.png)

**Comment by zpottie** [comment]
Hi there,

At the moment, the format is 'hard-coded' to that format. I'll see if I can make it customisable for the user using a setting perhaps - offering common formats like dd/mm/yyyy, mm-dd-yyyy, dd Month yyyy, etc.

Will post any updates and eventual fix here. Can't promise any ETA, sorry, but will do as soon as possible

Any extra formats or pull requests are always welcome! :)

**Comment by zpottie** [comment]
Hi @jprovasnik 

Just letting you know this is now available from f7206b9 onwards.

When you've updated the plugin, you will see a new setting to customise the date format is available.

Hope that helps! 😄 

Thanks,
Zander
