### ISSUE TITLE
Add capability to allow any role to create/manage notifications

### ISSUE THREAD

**Issue by zpottie** [learningworks/moodle-block_advnotifications#24]
Currently a teacher (for example) can't add a new notification to a block. A common use-case may be for teachers to add notifications to their course - not globally.

I believe the capabilities are not set up correctly - likely the contexts. But also, finer granularity is needed. For example, a capability to only add non-global notifications, ideal for teachers, ensuring the notification is not shown in other contexts it wasn't intended for.

This issue was initially raised at [https://moodle.org/plugins/block_advnotifications](https://moodle.org/plugins/block_advnotifications)

**Comment by jprovasnik** [comment]
I have a similar request, but, I don't need them to be able to add their own block -- they can already do this. Once the block is added at the course level, I teachers to be able to see the "Manage Notifications" link. I guess I'm confused how this is a bug because wasn't the block created so teachers can add notifications into their course? When the block is added at the course context and teachers are given the "Edit a block's settings" I'm confused as to why they cannot see the manage the notifications link. Thanks!

**Comment by jprovasnik** [comment]
OK, I think I just had a bad configuration -- I gave my 'teacher' role this ability and it did not work at the course level. however, I have a global role for all my staff and when I gave the permission to the global role, it then worked at the course level.-- . I can now get my teacher to see this link at the course level on the course-context adv notification block. Not sure what the clearest solution is here, but... I have 389 Moodle courses, and though it was a long task, I've added the Adv notification block at the course level in every shell myself. This way, when the teacher turns editing mode on, they can see the block and add an announcement. I have one one the front page as well, so if i add an announcement, it pushes down into all courses (but not the other way around).

**Comment by zpottie** [comment]
Hi @jprovasnik - I've updated the plugin.

It now allows an admin to give permissions/capabilities to roles to be able to create and manage their own notifications (from 4a23378 and up). This allows, for example, teachers to be given the permission `manageownnotifications` and therefore create/manage notifications in their course(s). They should see the 'Manage Notifications" in the dropdown now and they should only be able to see & edit their own notifications on the 'Manage' page. These notifications are limited to the block they are created from - users that only have the `manageownnotifications` permission can not make **global** notifications.

Hope this helps! 😃
