### ISSUE TITLE
Warning:  key() expects parameter 1 to be array, string given in /moodle/blocks/advnotifications/settings.php on line 101

### ISSUE THREAD

**Issue by rbruch** [learningworks/moodle-block_advnotifications#25]
Upgrading from 1.3.9 to 1.3.11, on the upgradesettings.php page see the following warning:

"Warning: key() expects parameter 1 to be array, string given in [path]/moodle/blocks/advnotifications/settings.php on line 101"

Also am seeing it on the Site Administration page (/moodle/admin/search.php). I have _Debug messages_ set to DEVELOPER and _Display debug messages_ to Yes on my development site where I am seeing the warning. The message goes away if I turn _Display debug messages_ off. 

The plugin seems to function as expected but perhaps the warning should be addressed?

Versions:
Moodle 3.5.14
PHP 7.2.24

**Comment by zpottie** [comment]
Hi @rbruch! 

Thanks for reporting this! I have no idea why, but my debugging setting was turned off before I pushed the latest version 🤦 

I've pushed a fix, so should no longer see the warning from 225e48a onwards.

Will push the update to the Moodle Plugins directory soon.

Thanks again,
Zander

**Comment by zpottie** [comment]
Latest version uploaded to https://moodle.org/plugins/block_advnotifications

I will close this now.

Thanks again! :)
