### ISSUE TITLE
Debug info: ERROR: value "32768" is out of range for type smallint

### ISSUE THREAD

**Issue by caiado** [learningworks/moodle-block_advnotifications#27]
Moodle 3.8.5+
PostgreSQL 12
PHP 7.4
Ubuntu 20.04

-------------------------------------------

Debug info: ERROR: value "32768" is out of range for type smallint
UPDATE mdl_block_advnotificationsdissed SET seen = $1 WHERE id=$2
[array (
'seen' => 32768,
0 => '1',
)]
Error code: dmlwriteexception
Stack trace:

    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 259 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 1184 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 1217 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->update_record_raw()
    line 99 of /blocks/advnotifications/locallib.php: call to pgsql_native_moodle_database->update_record()
    line 66 of /blocks/advnotifications/block_advnotifications.php: call to prep_notifications()
    line 341 of /blocks/moodleblock.class.php: call to block_advnotifications->get_content()
    line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 91 of /blocks/advnotifications/block_advnotifications.php: call to block_base->get_content_for_output()
    line 1181 of /lib/blocklib.php: call to block_advnotifications->get_content_for_output()
    line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
    line 3920 of /lib/outputrenderers.php: call to block_manager->region_has_content()
    line 49 of /theme/fordson/layout/frontpage.php: call to core_renderer->blocks()
    line 1374 of /lib/outputrenderers.php: call to include()
    line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 100 of /index.php: call to core_renderer->header()

**Comment by zpottie** [comment]
Hi @caiado,

Looks like that notification has been seen a whopping 32767 times! 🤯 

I'll update the next release of the plugin to either increase the maximum allowed 'seen' number or add a check if we've reached the maximum.

For now, a work-around would be to re-create the exact same notification - that way it will appear the same to users, but it will start counting from `0` again.

Or, possibly running (**untested, _please_ test on test-site first**) in the database:
```pgsql
UPDATE mdl_block_advnotificationsdissed SET seen = 1 WHERE id=1
```
<sup>(will reset that specific user's view times of that notification to 1)</sup>
or
```pgsql
UPDATE mdl_block_advnotificationsdissed SET seen = 1 WHERE seen > 32000
```
<sup>(will reset all notification views of more than 32000 - close to max of 32767 - to 1)</sup>

Hope this helps in the meantime, thanks for reporting with detailed info! 😃 

Thanks,
Zander

**Comment by zpottie** [comment]
**For reference...**
Different DB's handle XMLDB's `int` type and `LENGTH` differently:
https://docs.moodle.org/dev/XMLDB_column_types

**Comment by caiado** [comment]
Zander,

Our list of users go beyond 250K.

Ricardo

**Comment by zpottie** [comment]
That's impressive. Even more-so, because the 'seen' field tracks each notification per-user. So a single user (perhaps admin?) has had a notification shown to them that many times.

I've pushed an update (826a322) to increase the maximum seen amount significantly. As per BIGINT:
* PostgreSQL - https://www.postgresql.org/docs/9.1/datatype-numeric.html
* MySQL - https://dev.mysql.com/doc/refman/8.0/en/integer-types.html

Will just wait for TravisCI to finish successfully, and then I'll update it on Moodle Plugins Directory.

Thanks again,
Zander

**Comment by caiado** [comment]
Thank you!

**Comment by zpottie** [comment]
Have released the new version on Moodle Plugins Directory - https://moodle.org/plugins/block_advnotifications

Cheers!
<sub>Will close this issue now</sub>
