### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by XTRage** [learningworks/moodle-block_advnotifications#28]
So we have few unit test failures, they do not influence the workflow itself but it would be nice to have it pass everything.

1) provider_testcase::test_metadata_provider with data set "block_advnotifications" ('block_advnotifications', 'block_advnotifications\privac...ovider')
Failed asserting that false is true.

/moodle/privacy/tests/provider_test.php:131
/moodle/lib/phpunit/classes/advanced_testcase.php:80

This one seems to fail because lines 72 and 85 of blocks/advnotifications/classes/privacy/provider.php (in release 1.4.1) do not have "block_" prefix for table names.

Additional thing is that you print output in testcases which marks them as risky, but that is already nitpicking.

**Comment by zpottie** [comment]
Thanks @XTRage - I see what you mean about the table names - will push a fix for that.

Not sure what you mean with the last sentence though? Where am I printing output in testcases? Is that not Moodle/PHPUnit doing so? Currently, the plugin doesn't have automated tests included with the plugin (except TravisCI) and  'provider_testcase::test_metadata_provider' is executed by core Moodle from `/moodle/privacy/tests/provider_test.php:115` (Moodle v3.9)

**Comment by XTRage** [comment]
Thank you for your quick reply.

About the other thing:

There was 1 risky test:
1) provider_testcase::test_component_understands_deleted_users with data set "block_advnotifications" ('block_advnotifications', 'block_advnotifications\privac...ovider')
This test printed output: 	Getting contexts for userid...
	Done 'Getting contexts for userid...'

It is just about printing some output during the test (you are doing it with mtrace) and PHPUnit marking those as "risky" tests with its out-of-the-box Moodle configuration/distribution.
But as I said, just nitpicking, PHPUnit shuts up when "beStrictAboutOutputDuringTests" is set to false.

**Comment by zpottie** [comment]
Thanks again for the report and detailed info, @XTRage! Thanks to Open Source magic, @gustavorivas96 has addressed the above issues in the latest pull request. 👌 

I'll push the fixes to the Moodle Plugins directory as soon as I can.
