### ISSUE TITLE
Improvement: Convert custom.js into AMD modules

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-block_advnotifications#4]
https://docs.moodle.org/dev/Javascript_Modules

**Comment by zpottie** [comment]
Thanks again David - will look into this.

**Comment by mkpelletier** [comment]
I have to upvote this one.  Not including javascript as AMD breaks Moodle in certain cases.  Depending on what other plugins are installed, users may see a "Mismatch anonymous define" javascript error.  

With only a couple of javascript libraries in this module, it should be pretty easy to convert them to AMD.

**Comment by zpottie** [comment]
JS has been converted to use AMD format. Closing...
