### ISSUE TITLE
DB queries in the renderer

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-block_advnotifications#5]
Renderers should not ever touch the database. The actual logic of obtaining data to render should stand outside the output rendering logic.

Additionally, SQL queries should not be called in loops. The number of SQL queries should remain constant regardless the number of notifications to display. Ideally you should be able to fetch all data in one query and pass them to the renderer.

**Comment by zpottie** [comment]
Makes sense - I will move it out in a future update (hopefully soon).

**Comment by zpottie** [comment]
Moved DB queries out of renderer file. Renderer now only used to output/render notification.
